title: Ricardo Kleinlein's Notes
name: "Ricardo Kleinlein's Notes"
author: Ricardo Kleinlein
description: 

baseurl: ""
url: "http://ricardokleinklein.github.io"

footer-links:
  email: ricardokleinklein@gmail.com
  github: ricardokleinklein
  instagram: ricardokleinklein
  google_scholar: citations?user=TEoDo4wAAAAJ&hl=en

disqus: https-ricardokleinklein-github-io

# Build settings
markdown: krandown
excerpt_separator: <!--eoe-->
kramdown:
  input: GFM
  auto_ids: true
  toc_levels: 1..1
plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock

sass:
  sass_dir: _sass
  style: compressed
